import { defineConfig } from './keylion.config.js'

export default defineConfig({
    name: 'Keylion',
    namespace: 'k',
    host: 'localhost',
    port: 8080,
    title: 'KEYLION',
    format: "esm",
    logo: 'https://varlet.gitee.io/varlet-ui/varlet_icon.png',
    defaultLanguage: "zh-CN",
    analysis: {
        baidu: ''
    },
    uniapp: {
        uniappConfig: {
            "globalStyle": {
                "navigationBarTextStyle": "black",
                "navigationBarTitleText": "uni-app",
                "navigationBarBackgroundColor": "#F8F8F8",
                "backgroundColor": "#F8F8F8"
            }
        },
        server: {
            port: 3000
        }

    },
    themeKey: "KEYLION_THEME",
    lightTheme: {
        'color-body': '#fff',
        'color-index-page-background': '#f2f2f2',
        'color-index-page-feature-background': '#fff',
        'color-index-page-logo-mask-background': 'linear-gradient(-45deg, #8baff8 50%, #84e0ff 50%)',
        'color-index-page-second-text-color': 'rgba(60, 60, 60, .7)',
        'color-index-page-divider-color': '#ddd',
        'color-bar': '#fff',
        'color-sub-bar': '#f5f5f5',
        'color-text': '#555',
        'color-sub-text': '#888',
        'color-border': 'rgba(0, 0, 0, 0.12)',
        'color-shadow': '#eee',
        'color-introduce-border': '#2196f3',
        'color-primary': '#2196f3',
        'color-link': '#00c48f',
        'color-type': '#00c48f',
        'color-loading-bar': '#1d92e9',
        'color-side-bar': '#3a7afe',
        'color-side-bar-active-background': '#3a7afe1a',
        'color-app-bar': '#3a7afe',
        'color-nav-button-hover-background': 'rgba(0, 0, 0, 0.08)',
        'color-mobile-cell-hover': '#3a7afe',
        'color-pc-language-active': '#3a7afe',
        'color-pc-language-active-background': '#edf5ff',
        'color-pc-github-active-background': '#212121',
        'color-mobile-language-active': '#3a7afe',
        'color-mobile-language-active-background': '#edf5ff',
        'color-hl-background': '#fafafa',
        'color-hl-code': '#58727e',
        'color-hl-border': '#f3f3f3',
        'color-hl-group-a': '#7c7c7c',
        'color-hl-group-b': '#2196f3',
        'color-hl-group-c': '#ff9422',
        'color-hl-group-d': '#58c193',
        'color-hl-group-e': '#ff9422',
        'color-hl-group-f': '#ff9422',
        'color-hl-group-g': '#ff9422',
        'color-hl-group-h': '#06a6e9',
        'color-hl-group-i': '#f23733',
    },
    darkTheme: {
        'color-body': '#121212',
        'color-index-page-background': '#1e1e1e',
        'color-index-page-feature-background': '#303030',
        'color-index-page-logo-mask-background': 'linear-gradient(-45deg, #729dfc 50%, #6859f4 50%)',
        'color-index-page-second-text-color': 'rgba(255, 255, 255, .75)',
        'color-index-page-divider-color': 'rgba(84, 84, 84, .8)',
        'color-bar': '#1e1e1e',
        'color-sub-bar': '#272727',
        'color-text': '#fff',
        'color-sub-text': '#aaa',
        'color-border': '#333',
        'color-shadow': '#121212',
        'color-introduce-border': '#555',
        'color-primary': '#96cbfe',
        'color-link': '#A8FFC4',
        'color-type': '#A8FFC4',
        'color-loading-bar': '#5580f8',
        'color-side-bar': '#4a7afe',
        'color-side-bar-active-background': '#4a7afe1a',
        'color-app-bar': '#272727',
        'color-nav-button-hover-background': 'rgba(255, 255, 255, 0.08)',
        'color-mobile-cell-hover': '#4a7afe',
        'color-pc-language-active': '#4a7afe',
        'color-pc-language-active-background': '#4a7afe20',
        'color-pc-github-active-background': '#303030',
        'color-mobile-language-active': '#4a7afe',
        'color-mobile-language-active-background': '#4a7afe20',
        'color-hl-background': '#272727',
        'color-hl-code': '#fff',
        'color-hl-border': '#272727',
        'color-hl-group-a': '#7c7c7c',
        'color-hl-group-b': '#96cbfe',
        'color-hl-group-c': '#ff7b1e',
        'color-hl-group-d': '#A8FFC4',
        'color-hl-group-e': '#ff7b1e',
        'color-hl-group-f': '#ff7b1e',
        'color-hl-group-g': '#ff7b1e',
        'color-hl-group-h': '#14a6e9',
        'color-hl-group-i': '#ed4648',
    }
})