export declare const dirname: string;
export declare const CWD: string;
export declare const KEYLION_CONFIG: string;
export declare const SRC_DIR: string;
export declare const ES_DIR: string;
export declare const SITE_OUTPUT_PATH: string;
export declare const LIB_DIR: string;
export declare const UMD_DIR: string;
export declare const TYPES_DIR: string;
export declare const ROOT_DOCS_DIR: string;
export declare const ROOT_PAGES_DIR: string;
export declare const ESLINT_EXTENSIONS: string[];
export declare const FILE_EXTENSION: string[];
export declare const scriptExtNames: string[];
export declare const ignoreFile: string[];
export declare const VITE_RESOLVE_EXTENSIONS: string[];
export declare const SCRIPTS_EXTENSIONS: string[];
export declare const PUBLIC_DIR_INDEXES: string[];
export declare const STYLE_DIR_NAME = "style";
export declare const EXAMPLE_DIR_NAME = "example";
export declare const LOCALE_DIR_NAME = "locale";
export declare const DOCS_DIR_NAME = "docs";
export declare const TEST_DIR_NAME = "__tests__";
export declare const CLI_PACKAGE_JSON: string;
export declare const UI_PACKAGE_JSON: string;
export declare const IMPORT_FROM_DEPEDENCE_RE: RegExp;
export declare const EXPORT_FROM_DEPEDENCE_RE: RegExp;
export declare const IMPORT_DEPEDENCE_RE: RegExp;
export declare const STYLE_EXTENSIONS: string[];
export declare const STYLE_EXTENSION: string[];
export declare const SCSS_RE: RegExp;
export declare const CSS_RE: RegExp;
export declare const LESS_RE: RegExp;
export declare const STYLE_IMPORT_RE: RegExp;
export declare const SITE: string;
export declare const SITE_DIR: string;
export declare const SITE_PUBLIC_PATH: string;
export declare const SITE_CONFIG: string;
export declare const SITE_PC: string;
export declare const SITE_MOBILE: string;
export declare const TEMPLATE: string;
